### PR TITLE
Add postgresql role

### PR DESCRIPTION
**Pull request by notFloran**
#24

### CODE REVIEW

**Comment by notFloran** [comment]
@nclsHart can you try ?

**Comment by nclsHart** [comment]
It fail on my machine: 

```
TASK [postgresql : Check if user database exists] ************************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => changed=false
  cmd: psql -lqt | cut -d \| -f 1 | grep -qw nhart
  delta: '0:00:00.063838'
  end: '2019-05-09 14:14:17.592764'
  msg: non-zero return code
  rc: 1
  start: '2019-05-09 14:14:17.528926'
  stderr: ''
  stderr_lines: []
  stdout: ''
  stdout_lines: <omitted>
```

**Comment by notFloran** [comment]
@nclsHart can you retry

**Comment by nclsHart** [comment]
Fixed 👍.

**Pull request merged**
